### ISSUE TITLE
Thread Safety Issues?

### ISSUE THREAD

**Issue by thieman** [agoragames/bnet_scraper#12]
I'm getting two sets of values returned for this profile URL (http://us.battle.net/sc2/en/profile/273698/1/Omni/) for career games and games this season.

Set 1 (correct): {career_games: '205', games_this_season: '41'}
Set 2 (incorrect): {career_games: '226', games_this_season: '47'}

This is interesting to me because it's always from these two sets; there's no further variation. I haven't seen this happen in a single-threaded model, and it suddenly appeared once I went multi-thread, so I think that might be the likely culprit. Maybe I'm wrong, though.

Code: http://pastebin.com/Zjx2iVFi

**Comment by thieman** [comment]
Upon further review, the Battle.net profile itself is actually changing on repeated refresh (what in the world?). Maybe I'll file a bug report with Blizzard.

**Comment by thieman** [comment]
Hey @cadwallion, this isn't a problem with the library, but do you have any idea what's going on here? Have you seen it before?

**Comment by cadwallion** [comment]
I can't say I've ever seen that problem on their site before.  I can reproduce what you're experiencing just by hitting refresh on the profile page, though.
