### ISSUE TITLE
Most of the example of the help welcome page are not working.

### ISSUE THREAD

**Issue by ghost** [agoragames/bnet_scraper#18]
Hello there again,
please would you kindly check and update all examples on the first main page ?
Some of them are not working.

Thanks a lot!
Cheers

**Comment by cadwallion** [comment]
Wow...yeah, it seems that when I overhauled the API in #10 I neglected the documentation.  I have started working on it this morning, and will have it completed by tonight.  Apologies for the inconsistencies.

**Comment by ghost** [comment]
No problem.
Thanks for taking care, and the fix for the dates you just did.
I'll try during the week again.

Courage! I like your tool

Cheers
